//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelFirstPractise.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BorrowedBooks
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BorrowedBooks()
        {
            this.IsReturned = false;
        }
    
        public int Id { get; set; }
        public int UserId { get; set; }
        public int BookId { get; set; }
        public System.DateTime DateBorrowed { get; set; }
        public Nullable<System.DateTime> DateToReturn { get; set; }
        public bool IsReturned { get; set; }
        public string DateReturned { get; set; }
        public int AdminId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
    
        public virtual Administrators Administrator { get; set; }
        public virtual Users User { get; set; }
        public virtual Books Book { get; set; }
    }
}
